### ISSUE TITLE
Invalid HTTP response code

### ISSUE THREAD

**Issue by jgardynik** [mongoose-os-libs/ota-http-client#3]
I'm setting up ota-http-client with an address that will check to see whether there's a new firmware to deliver and then deliver it if there is. If there isn't a new firmware, currently I'm returning HTTP/1.1 204 No Content, which apparently is an Invalid HTTP response code according to the log files (even if it is the most accurate response code I could be using and is perfectly valid).

```[Mar  7 18:01:18.722] RP-2000-A2A0F9 396 6845.125 2 0|mgos_ota_http_clien:102 Invalid HTTP response code```

What should I be returning in the event that there's not a new firmware for it to download when it polls? The documentation is rather nonexistent on this method of updating, and I can't really find out myself since all the OTA methods are locked up in inaccessible code due to the licensing restrictions.

**Comment by rojer** [comment]
"304 Not Modified" is the "nothing to see here, please move along" response.

**Comment by rojer** [comment]
for the server side, you can use https://github.com/cesanta/mongoose-os/blob/master/tools/updateredirector/updateredirector.go as an example

**Comment by jgardynik** [comment]
That works! Thanks for the quick response. Perhaps that should be included in the readme to help other people have a reference. :)

**Comment by rojer** [comment]
good idea, done
